"""
PDF Report generation utilities
"""
import json
import logging
from datetime import datetime
from io import BytesIO
from math import ceil
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

logger = logging.getLogger(__name__)

SHOW_EMPTY_DESKS = False

PAGE_SIZE = landscape(A4)
PAGE_WIDTH, PAGE_HEIGHT = PAGE_SIZE
LEFT_MARGIN = 0.45 * inch
RIGHT_MARGIN = 0.45 * inch
TOP_MARGIN = 2.55 * inch
BOTTOM_MARGIN = 0.65 * inch
CONTENT_WIDTH = PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN

HEADER_TITLE = "EXAM SEATING PLAN"
FOOTER_TEXT = "Generated by Sitting Plan System"


def _safe_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        try:
            return json.dumps(value, ensure_ascii=False)
        except (TypeError, ValueError):
            return str(value)
    return str(value)


def safe_pdf_text(value) -> str:
    text = _safe_text(value)
    text = text.replace("\x00", "")
    text = text.replace("\r", " ")
    lines = [escape(segment) for segment in text.split("\n")]
    return "<br/>".join(lines)


def _safe_paragraph(elements: list, value, style, context: str) -> None:
    sanitized_value = safe_pdf_text(value)
    logger.info(
        "reports.pdf.paragraph_payload",
        extra={
            "context": context,
            "raw_type": type(value).__name__,
            "preview": _safe_text(value)[:200],
        },
    )
    try:
        elements.append(Paragraph(sanitized_value, style))
    except Exception:
        logger.exception(
            "reports.pdf.paragraph_failure",
            extra={
                "context": context,
                "raw_type": type(value).__name__,
                "raw_preview": _safe_text(value)[:500],
                "sanitized_preview": sanitized_value[:500],
            },
        )
        raise


def _build_styles():
    styles = getSampleStyleSheet()
    return {
        "section_heading": ParagraphStyle(
            "SeatingSectionHeading",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=14,
            textColor=colors.HexColor("#12355B"),
            spaceAfter=8,
            spaceBefore=4,
        ),
        "summary_value": ParagraphStyle(
            "SeatingSummaryValue",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=16,
            textColor=colors.HexColor("#0F172A"),
            alignment=TA_CENTER,
        ),
        "summary_label": ParagraphStyle(
            "SeatingSummaryLabel",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#475569"),
            alignment=TA_CENTER,
        ),
        "table_header": ParagraphStyle(
            "SeatingTableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            alignment=TA_CENTER,
            textColor=colors.white,
        ),
        "table_name": ParagraphStyle(
            "SeatingTableName",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            leading=9,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#0F172A"),
            wordWrap="CJK",
        ),
        "table_center": ParagraphStyle(
            "SeatingTableCenter",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            leading=9,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#0F172A"),
            wordWrap="CJK",
        ),
        "table_batch": ParagraphStyle(
            "SeatingTableBatch",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7,
            leading=8.5,
            alignment=TA_LEFT,
            textColor=colors.HexColor("#1E293B"),
            wordWrap="CJK",
        ),
        "small_note": ParagraphStyle(
            "SeatingSmallNote",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#475569"),
        ),
    }


def _normalize_assignment(plan_data: dict) -> list[tuple[str, list[dict]]]:
    assignment = plan_data.get("assignment", {})
    if not isinstance(assignment, dict):
        return []

    normalized: list[tuple[str, list[dict]]] = []
    for desk_id, students in assignment.items():
        student_rows = students if isinstance(students, list) else []
        normalized.append((str(desk_id), [item for item in student_rows if isinstance(item, dict)]))

    def _desk_sort_key(item: tuple[str, list[dict]]):
        raw = item[0].strip()
        if raw.isdigit():
            return (0, int(raw))
        digits = "".join(ch for ch in raw if ch.isdigit())
        if digits:
            return (0, int(digits))
        return (1, raw.lower())

    normalized.sort(key=_desk_sort_key)
    return normalized


def _batch_distribution(plan_data: dict, assignment_rows: list[tuple[str, list[dict]]]) -> list[tuple[str, int]]:
    distribution = plan_data.get("batch_distribution")
    if isinstance(distribution, list):
        rows = []
        for item in distribution:
            if isinstance(item, dict) and item.get("batch"):
                rows.append((str(item["batch"]), int(item.get("count") or 0)))
        rows = [(batch, count) for batch, count in rows if count > 0]
        if rows:
            return rows

    counts: dict[str, int] = {}
    for _, students in assignment_rows:
        for student in students:
            batch_name = str(student.get("batch") or "").strip() or "Unspecified"
            counts[batch_name] = counts.get(batch_name, 0) + 1
    return sorted(counts.items(), key=lambda item: (-item[1], item[0].lower()))


def _format_plan_type(value) -> str:
    text = str(value or "N/A").replace("_", " ").strip()
    return text.title() if text else "N/A"


def _format_datetime(value) -> str:
    if not value:
        return datetime.now().strftime("%d %b %Y, %I:%M %p")
    text = str(value).strip()
    if not text:
        return datetime.now().strftime("%d %b %Y, %I:%M %p")
    try:
        normalized = text.replace("Z", "+00:00")
        return datetime.fromisoformat(normalized).strftime("%d %b %Y, %I:%M %p")
    except ValueError:
        return text


def _make_paragraph(value, style):
    return Paragraph(safe_pdf_text(value or "-"), style)


def _build_header_context(plan_data: dict, room_data: dict, summary: dict) -> dict:
    exam = plan_data.get("exam", {}) if isinstance(plan_data.get("exam"), dict) else {}
    return {
        "institute_name": room_data.get("institute_name") or plan_data.get("institute_name") or "Institute Name Not Available",
        "exam_name": room_data.get("exam_name") or exam.get("name") or "N/A",
        "plan_type": _format_plan_type(room_data.get("plan_type") or plan_data.get("plan_type")),
        "room_name": room_data.get("name") or "N/A",
        "capacity": _safe_text(room_data.get("capacity") or "N/A"),
        "students_assigned": _safe_text(summary["students_assigned"]),
        "generated_date": _format_datetime(
            room_data.get("generated_at")
            or room_data.get("created_at")
            or plan_data.get("generated_at")
            or plan_data.get("created_at")
        ),
    }


def _draw_header(canvas_obj: canvas.Canvas, doc: SimpleDocTemplate, header: dict) -> None:
    title_y = PAGE_HEIGHT - 28
    canvas_obj.setFillColor(colors.HexColor("#12355B"))
    canvas_obj.setFont("Helvetica-Bold", 18)
    canvas_obj.drawString(LEFT_MARGIN, title_y, HEADER_TITLE)

    canvas_obj.setFillColor(colors.HexColor("#334155"))
    canvas_obj.setFont("Helvetica-Bold", 11)
    canvas_obj.drawString(LEFT_MARGIN, title_y - 16, _safe_text(header["institute_name"]))

    info_rows = [
        ("Exam Name", header["exam_name"]),
        ("Plan Type", header["plan_type"]),
        ("Room Name", header["room_name"]),
        ("Capacity", header["capacity"]),
        ("Students Assigned", header["students_assigned"]),
        ("Generated Date", header["generated_date"]),
    ]

    box_width = (CONTENT_WIDTH - 10) / 3
    box_height = 34
    start_y = PAGE_HEIGHT - 78

    for index, (label, value) in enumerate(info_rows):
        col = index % 3
        row = index // 3
        x = LEFT_MARGIN + col * (box_width + 5)
        y = start_y - row * (box_height + 6)

        canvas_obj.setStrokeColor(colors.HexColor("#CBD5E1"))
        canvas_obj.setFillColor(colors.HexColor("#F8FAFC"))
        canvas_obj.roundRect(x, y, box_width, box_height, 4, fill=1, stroke=1)

        canvas_obj.setFillColor(colors.HexColor("#64748B"))
        canvas_obj.setFont("Helvetica-Bold", 7)
        canvas_obj.drawString(x + 8, y + box_height - 11, label.upper())

        value_style = ParagraphStyle(
            "HeaderValue",
            fontName="Helvetica",
            fontSize=8.5,
            leading=10,
            textColor=colors.HexColor("#0F172A"),
            alignment=TA_LEFT,
            wordWrap="CJK",
        )
        value_paragraph = Paragraph(safe_pdf_text(_safe_text(value)[:120]), value_style)
        width, height = value_paragraph.wrap(box_width - 16, 16)
        value_paragraph.drawOn(canvas_obj, x + 8, y + max(8, 10 - max(0, height - 10)))

    canvas_obj.setStrokeColor(colors.HexColor("#CBD5E1"))
    canvas_obj.line(LEFT_MARGIN, PAGE_HEIGHT - 162, PAGE_WIDTH - RIGHT_MARGIN, PAGE_HEIGHT - 162)


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, header_context=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self._header_context = header_context or {}

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_chrome(page_count)
            super().showPage()
        super().save()

    def _draw_page_chrome(self, page_count: int):
        _draw_header(self, None, self._header_context)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.line(LEFT_MARGIN, BOTTOM_MARGIN - 8, PAGE_WIDTH - RIGHT_MARGIN, BOTTOM_MARGIN - 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.setFont("Helvetica", 8)
        self.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 22, FOOTER_TEXT)
        self.drawRightString(
            PAGE_WIDTH - RIGHT_MARGIN,
            BOTTOM_MARGIN - 22,
            f"Page {self._pageNumber} of {page_count}",
        )


def _build_summary_table(summary: dict, styles: dict) -> Table:
    cards = [
        ("Total Students", summary["students_assigned"]),
        ("Total Occupied Desks", summary["occupied_desks"]),
        ("Total Empty Desks", summary["empty_desks"]),
        ("Room Utilization %", f"{summary['utilization_percent']}%"),
    ]

    row = []
    for label, value in cards:
        row.append(
            Table(
                [[
                    Paragraph(safe_pdf_text(str(value)), styles["summary_value"]),
                    Paragraph(safe_pdf_text(label), styles["summary_label"]),
                ]],
                colWidths=[(CONTENT_WIDTH - 18) / 4],
            )
        )

    summary_table = Table([row], colWidths=[(CONTENT_WIDTH - 18) / 4] * 4)
    summary_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ])
    )

    for card in row:
        card.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
                ("ROUNDEDCORNERS", [6, 6, 6, 6]),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ])
        )

    return summary_table


def _build_seating_table(assignment_rows: list[tuple[str, list[dict]]], styles: dict) -> Table:
    header_row = [
        _make_paragraph("Desk No", styles["table_header"]),
        _make_paragraph("Student 1 Name", styles["table_header"]),
        _make_paragraph("Student 1 Roll", styles["table_header"]),
        _make_paragraph("Student 1 Batch", styles["table_header"]),
        _make_paragraph("Student 2 Name", styles["table_header"]),
        _make_paragraph("Student 2 Roll", styles["table_header"]),
        _make_paragraph("Student 2 Batch", styles["table_header"]),
    ]

    table_rows = [header_row]
    for desk_number, students in assignment_rows:
        seat_1 = students[0] if len(students) >= 1 else {}
        seat_2 = students[1] if len(students) >= 2 else {}
        table_rows.append([
            _make_paragraph(desk_number, styles["table_center"]),
            _make_paragraph(seat_1.get("name") or "-", styles["table_name"]),
            _make_paragraph(seat_1.get("roll_number") or "-", styles["table_center"]),
            _make_paragraph(seat_1.get("batch") or "-", styles["table_batch"]),
            _make_paragraph(seat_2.get("name") or "-", styles["table_name"]),
            _make_paragraph(seat_2.get("roll_number") or "-", styles["table_center"]),
            _make_paragraph(seat_2.get("batch") or "-", styles["table_batch"]),
        ])

    col_widths = [
        0.65 * inch,
        1.95 * inch,
        1.10 * inch,
        1.70 * inch,
        1.95 * inch,
        1.10 * inch,
        1.70 * inch,
    ]

    table = Table(table_rows, colWidths=col_widths, repeatRows=1, splitByRow=1)
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#12355B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("TOPPADDING", (0, 0), (-1, 0), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#94A3B8")),
            ("INNERGRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#CBD5E1")),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 1), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
            ("ALIGN", (0, 1), (0, -1), "CENTER"),
            ("ALIGN", (2, 1), (2, -1), "CENTER"),
            ("ALIGN", (5, 1), (5, -1), "CENTER"),
        ])
    )
    return table


def _build_batch_summary_table(batch_rows: list[tuple[str, int]], styles: dict) -> Table:
    table_rows = [[
        _make_paragraph("Batch", styles["table_header"]),
        _make_paragraph("Students", styles["table_header"]),
    ]]
    for batch_name, count in batch_rows:
        table_rows.append([
            _make_paragraph(batch_name, styles["table_name"]),
            _make_paragraph(str(count), styles["table_center"]),
        ])

    table = Table(table_rows, colWidths=[CONTENT_WIDTH - 1.1 * inch, 1.1 * inch], repeatRows=1)
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#12355B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#94A3B8")),
            ("INNERGRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (1, 1), (1, -1), "CENTER"),
        ])
    )
    return table


def create_seating_report_pdf(plan_data: dict, room_data: dict) -> BytesIO:
    """
    Generate a professional PDF report for a seating plan.
    """
    buffer = BytesIO()
    styles = _build_styles()

    assignment_rows = _normalize_assignment(plan_data)
    total_desks = len(assignment_rows)
    occupied_rows = [(desk_no, students) for desk_no, students in assignment_rows if students]
    printed_rows = occupied_rows if not SHOW_EMPTY_DESKS else assignment_rows
    students_assigned = sum(len(students) for _, students in assignment_rows)
    occupied_desks = len(occupied_rows)
    empty_desks = max(total_desks - occupied_desks, 0)
    room_capacity = int(room_data.get("capacity") or 0)
    utilization_percent = round((students_assigned / room_capacity) * 100) if room_capacity > 0 else 0

    summary = {
        "students_assigned": students_assigned,
        "occupied_desks": occupied_desks,
        "empty_desks": empty_desks,
        "utilization_percent": utilization_percent,
    }
    header_context = _build_header_context(plan_data, room_data, summary)
    batch_rows = _batch_distribution(plan_data, assignment_rows)

    doc = SimpleDocTemplate(
        buffer,
        pagesize=PAGE_SIZE,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title=f"Seating Plan - {header_context['room_name']}",
        author="Sitting Plan System",
    )

    elements = []
    _safe_paragraph(elements, "Room Summary", styles["section_heading"], "summary_heading")
    elements.append(_build_summary_table(summary, styles))
    elements.append(Spacer(1, 0.18 * inch))

    if not printed_rows:
        _safe_paragraph(
            elements,
            "No occupied desks are available for this seating plan.",
            styles["small_note"],
            "no_occupied_desks_note",
        )
    else:
        _safe_paragraph(elements, "Seating Table", styles["section_heading"], "seating_table_heading")
        elements.append(_build_seating_table(printed_rows, styles))

    if batch_rows:
        elements.append(Spacer(1, 0.18 * inch))
        _safe_paragraph(elements, "Students by Batch", styles["section_heading"], "students_by_batch_heading")
        elements.append(_build_batch_summary_table(batch_rows, styles))

    logger.info(
        "reports.pdf.layout_summary",
        extra={
            "room_name": header_context["room_name"],
            "students_assigned": students_assigned,
            "total_desks": total_desks,
            "printed_desks": len(printed_rows),
            "show_empty_desks": SHOW_EMPTY_DESKS,
            "estimated_pages": max(1, ceil(len(printed_rows) / 28)) if printed_rows else 1,
        },
    )

    doc.build(
        elements,
        canvasmaker=lambda *args, **kwargs: NumberedCanvas(*args, header_context=header_context, **kwargs),
    )
    buffer.seek(0)
    return buffer
