"""
Shared PDF generation foundation providing consistent header, footer,
page numbering, margins, and typography across all export modules.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from io import BytesIO
from typing import Any, Callable, Optional
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Frame,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    PageTemplate,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# ── Shared constants ─────────────────────────────────────────────
DEFAULT_MARGIN = 0.45 * inch  # ~11.4 mm
DEFAULT_TOP_MARGIN = 1.8 * inch
DEFAULT_BOTTOM_MARGIN = 0.75 * inch

FOOTER_TEXT = "Generated by Sitting Plan System"

# ── Colour palette (professional, print-friendly) ────────────────
NAVY = colors.HexColor("#12355B")
SLATE_700 = colors.HexColor("#334155")
SLATE_500 = colors.HexColor("#64748B")
SLATE_300 = colors.HexColor("#CBD5E1")
SLATE_200 = colors.HexColor("#E2E8F0")
SLATE_100 = colors.HexColor("#F1F5F9")
SLATE_50 = colors.HexColor("#F8FAFC")
WHITE = colors.white
DARK_TEXT = colors.HexColor("#0F172A")
MEDIUM_TEXT = colors.HexColor("#475569")
LIGHT_TEXT = colors.HexColor("#94A3B8")


# ── Text utilities ───────────────────────────────────────────────
def safe_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        try:
            return json.dumps(value, ensure_ascii=False)
        except (TypeError, ValueError):
            return str(value)
    return str(value)


def safe_pdf_text(value: Any) -> str:
    text = safe_text(value)
    text = text.replace("\x00", "")
    text = text.replace("\r", " ")
    lines = [escape(segment) for segment in text.split("\n")]
    return "<br/>".join(lines)


def fmt_timestamp(dt: Optional[datetime] = None) -> str:
    return (dt or datetime.now()).strftime("%d %b %Y, %I:%M %p")


def fmt_date_iso(dt: Optional[datetime] = None) -> str:
    return (dt or datetime.now()).strftime("%Y-%m-%d")


# ── Shared paragraph styles ──────────────────────────────────────
def build_shared_styles():
    return {
        "title": ParagraphStyle(
            "PDF_Title",
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=NAVY,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "PDF_Subtitle",
            fontName="Helvetica",
            fontSize=11,
            leading=14,
            textColor=SLATE_700,
            alignment=TA_CENTER,
            spaceAfter=12,
        ),
        "section_heading": ParagraphStyle(
            "PDF_SectionHeading",
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=14,
            textColor=NAVY,
            spaceAfter=8,
            spaceBefore=4,
        ),
        "table_header": ParagraphStyle(
            "PDF_TableHeader",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=10.5,
            alignment=TA_CENTER,
            textColor=WHITE,
        ),
        "table_body_left": ParagraphStyle(
            "PDF_TableBodyLeft",
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            alignment=TA_LEFT,
            textColor=DARK_TEXT,
        ),
        "table_body_center": ParagraphStyle(
            "PDF_TableBodyCenter",
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            alignment=TA_CENTER,
            textColor=DARK_TEXT,
        ),
        "table_body_bold": ParagraphStyle(
            "PDF_TableBodyBold",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            alignment=TA_LEFT,
            textColor=DARK_TEXT,
        ),
        "small_note": ParagraphStyle(
            "PDF_SmallNote",
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=MEDIUM_TEXT,
            alignment=TA_CENTER,
        ),
        "summary_value": ParagraphStyle(
            "PDF_SummaryValue",
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=16,
            textColor=DARK_TEXT,
            alignment=TA_CENTER,
        ),
        "summary_label": ParagraphStyle(
            "PDF_SummaryLabel",
            fontName="Helvetica",
            fontSize=8.5,
            leading=10.5,
            textColor=MEDIUM_TEXT,
            alignment=TA_CENTER,
        ),
        "footer_note": ParagraphStyle(
            "PDF_FooterNote",
            fontName="Helvetica",
            fontSize=7.5,
            leading=9,
            textColor=SLATE_500,
        ),
    }


def make_paragraph(value: Any, style: ParagraphStyle) -> Paragraph:
    return Paragraph(safe_pdf_text(value or "-"), style)


# ── Header/footer canvas ─────────────────────────────────────────
class _PageChromeCanvas(canvas.Canvas):
    """Draws header and footer on every page. Used internally by ReportPdfBuilder."""

    def __init__(
        self,
        *args,
        header_drawer: Optional[Callable] = None,
        footer_text: str = FOOTER_TEXT,
        page_width: float = 0,
        page_height: float = 0,
        left_margin: float = DEFAULT_MARGIN,
        right_margin: float = DEFAULT_MARGIN,
        bottom_margin: float = DEFAULT_BOTTOM_MARGIN,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict] = []
        self._header_drawer = header_drawer
        self._footer_text = footer_text
        self._pw = page_width
        self._ph = page_height
        self._lm = left_margin
        self._rm = right_margin
        self._bm = bottom_margin

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_chrome(page_count)
            super().showPage()
        super().save()

    def _draw_page_chrome(self, page_count: int):
        if self._header_drawer:
            self._header_drawer(self)
        # Footer line
        self.setStrokeColor(SLATE_300)
        self.setLineWidth(0.5)
        self.line(self._lm, self._bm - 6, self._pw - self._rm, self._bm - 6)
        # Footer text & page number
        self.setFillColor(SLATE_500)
        self.setFont("Helvetica", 7.5)
        self.drawString(self._lm, self._bm - 20, self._footer_text)
        ts = fmt_timestamp()
        self.drawString(self._lm, self._bm - 33, ts)
        self.drawRightString(
            self._pw - self._rm,
            self._bm - 20,
            f"Page {self._pageNumber} of {page_count}",
        )


# ── High-level builder ────────────────────────────────────────────
class ReportPdfBuilder:
    """Drop-in builder that creates a PDF with consistent chrome.

    Usage:
        builder = ReportPdfBuilder(buffer, pagesize=landscape(A4))
        builder.add_title("My Report")
        builder.add_subtitle("Institute Name")
        builder.add_section_heading("Details")
        builder.add_table(...)
        builder.build(header_context={...})
    """

    def __init__(
        self,
        buffer: BytesIO,
        pagesize=landscape(A4),
        left_margin: float = DEFAULT_MARGIN,
        right_margin: float = DEFAULT_MARGIN,
        top_margin: float = DEFAULT_TOP_MARGIN,
        bottom_margin: float = DEFAULT_BOTTOM_MARGIN,
        title: str = "",
        author: str = "Sitting Plan System",
        footer_text: str = FOOTER_TEXT,
        header_drawer: Optional[Callable] = None,
    ):
        self.buffer = buffer
        self.pw, self.ph = pagesize
        self.lm = left_margin
        self.rm = right_margin
        self.tm = top_margin
        self.bm = bottom_margin
        self.content_width = self.pw - self.lm - self.rm
        self.pagesize = pagesize
        self.footer_text = footer_text
        self._header_drawer = header_drawer

        self.doc = SimpleDocTemplate(
            buffer,
            pagesize=pagesize,
            leftMargin=left_margin,
            rightMargin=right_margin,
            topMargin=top_margin,
            bottomMargin=bottom_margin,
            title=title,
            author=author,
        )
        self.styles = build_shared_styles()
        self.elements: list = []

    def add_title(self, text: str) -> None:
        self.elements.append(Paragraph(safe_pdf_text(text), self.styles["title"]))

    def add_subtitle(self, text: str) -> None:
        self.elements.append(Paragraph(safe_pdf_text(text), self.styles["subtitle"]))

    def add_section_heading(self, text: str) -> None:
        self.elements.append(
            Paragraph(safe_pdf_text(text), self.styles["section_heading"])
        )

    def add_spacer(self, height: float = 0.15 * inch) -> None:
        self.elements.append(Spacer(1, height))

    def add_small_note(self, text: str) -> None:
        self.elements.append(Paragraph(safe_pdf_text(text), self.styles["small_note"]))

    def add_table(self, table: Table) -> None:
        self.elements.append(table)

    def add_keep_together(self, *items) -> None:
        """Wrap items in KeepTogether to prevent page breaks between them."""
        wrappable = []
        for item in items:
            if isinstance(item, list):
                wrappable.extend(item)
            else:
                wrappable.append(item)
        self.elements.append(KeepTogether(wrappable))

    def add_page_break(self) -> None:
        self.elements.append(PageBreak())

    def build(self, header_context: Optional[dict] = None) -> BytesIO:
        header_drawer = self._header_drawer
        if header_drawer and header_context:
            # Bind header context
            def _make_drawer(fn, ctx):
                def drawer(canv):
                    fn(canv, ctx)
                return drawer
            header_drawer = _make_drawer(header_drawer, header_context)

        self.doc.build(
            self.elements,
            canvasmaker=lambda *args, **kwargs: _PageChromeCanvas(
                *args,
                header_drawer=header_drawer,
                footer_text=self.footer_text,
                page_width=self.pw,
                page_height=self.ph,
                left_margin=self.lm,
                right_margin=self.rm,
                bottom_margin=self.bm,
                **kwargs,
            ),
        )
        self.buffer.seek(0)
        return self.buffer
