import { apiService } from '@services/api';

export const attendanceManagementService = {
  getAttendanceOverview: apiService.getAttendanceOverview.bind(apiService),
  getIntegratedAttendanceOverview: apiService.getIntegratedAttendanceOverview.bind(apiService),
  listAttendanceStudents: apiService.listAttendanceStudents.bind(apiService),
  listIntegratedStudents: apiService.listIntegratedStudents.bind(apiService),
  listAttendanceStaff: apiService.listAttendanceStaff.bind(apiService),
  listIntegratedStaff: apiService.listIntegratedStaff.bind(apiService),
  listAttendanceSubjects: apiService.listAttendanceSubjects.bind(apiService),
  getTeacherAttendanceContext: apiService.getTeacherAttendanceContext.bind(apiService),
  getBatchAttendanceContext: apiService.getBatchAttendanceContext.bind(apiService),
  getStudentAttendanceMarking: apiService.getStudentAttendanceMarking.bind(apiService),
  saveStudentAttendance: apiService.saveStudentAttendance.bind(apiService),
  listStudentAttendanceRecords: apiService.listStudentAttendanceRecords.bind(apiService),
  deleteStudentAttendanceRecord: apiService.deleteStudentAttendanceRecord.bind(apiService),
  deleteAllStudentAttendanceRecords: apiService.deleteAllStudentAttendanceRecords.bind(apiService),
  getStudentAttendanceDashboard: apiService.getStudentAttendanceDashboard.bind(apiService),
  getStaffAttendanceMarking: apiService.getStaffAttendanceMarking.bind(apiService),
  saveStaffAttendance: apiService.saveStaffAttendance.bind(apiService),
  listStaffAttendanceRecords: apiService.listStaffAttendanceRecords.bind(apiService),
  deleteStaffAttendanceRecord: apiService.deleteStaffAttendanceRecord.bind(apiService),
  deleteAllStaffAttendanceRecords: apiService.deleteAllStaffAttendanceRecords.bind(apiService),
  getStaffAttendanceDashboard: apiService.getStaffAttendanceDashboard.bind(apiService),
  listAttendanceLeaves: apiService.listAttendanceLeaves.bind(apiService),
  createAttendanceLeave: apiService.createAttendanceLeave.bind(apiService),
  decideAttendanceLeave: apiService.decideAttendanceLeave.bind(apiService),
  deleteAttendanceLeave: apiService.deleteAttendanceLeave.bind(apiService),
  deleteAllAttendanceLeaves: apiService.deleteAllAttendanceLeaves.bind(apiService),
  createAttendanceHoliday: apiService.createAttendanceHoliday.bind(apiService),
  deleteAttendanceHoliday: apiService.deleteAttendanceHoliday.bind(apiService),
  deleteAllAttendanceHolidays: apiService.deleteAllAttendanceHolidays.bind(apiService),
  deleteAttendanceNotification: apiService.deleteAttendanceNotification.bind(apiService),
  deleteAllAttendanceNotifications: apiService.deleteAllAttendanceNotifications.bind(apiService),
  getAttendanceReportData: apiService.getAttendanceReportData.bind(apiService),
  exportAttendanceReport: apiService.exportAttendanceReport.bind(apiService),
};
