"""initial_schema

Revision ID: a6379ccf231f
Revises: 
Create Date: 2026-05-07 23:06:21.627795
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a6379ccf231f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('otp_code', sa.String(length=20), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_email'), 'tokens', ['email'], unique=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'VIEWER', 'STORE_MANAGER', name='userrole'), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('attendance_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('holiday_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_holidays_holiday_date'), 'attendance_holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_attendance_holidays_id'), 'attendance_holidays', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_holidays_school_id'), 'attendance_holidays', ['school_id'], unique=False)
    op.create_table('attendance_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_notifications_id'), 'attendance_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_notifications_school_id'), 'attendance_notifications', ['school_id'], unique=False)
    op.create_table('attendance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('minimum_attendance_threshold', sa.Float(), nullable=False),
    sa.Column('working_hours_start', sa.String(length=10), nullable=False),
    sa.Column('working_hours_end', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_settings_id'), 'attendance_settings', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_settings_school_id'), 'attendance_settings', ['school_id'], unique=True)
    op.create_table('attendance_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_staff_department'), 'attendance_staff', ['department'], unique=False)
    op.create_index(op.f('ix_attendance_staff_id'), 'attendance_staff', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_staff_school_id'), 'attendance_staff', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_staff_staff_id'), 'attendance_staff', ['staff_id'], unique=False)
    op.create_table('attendance_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('parent_contact', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_students_class_name'), 'attendance_students', ['class_name'], unique=False)
    op.create_index(op.f('ix_attendance_students_id'), 'attendance_students', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_students_roll_no'), 'attendance_students', ['roll_no'], unique=False)
    op.create_index(op.f('ix_attendance_students_school_id'), 'attendance_students', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_students_section'), 'attendance_students', ['section'], unique=False)
    op.create_table('attendance_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_subjects_class_name'), 'attendance_subjects', ['class_name'], unique=False)
    op.create_index(op.f('ix_attendance_subjects_id'), 'attendance_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_subjects_school_id'), 'attendance_subjects', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_subjects_section'), 'attendance_subjects', ['section'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('syllabus', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_category'), 'batches', ['category'], unique=False)
    op.create_index(op.f('ix_batches_display_order'), 'batches', ['display_order'], unique=False)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_name'), 'batches', ['name'], unique=False)
    op.create_index(op.f('ix_batches_school_id'), 'batches', ['school_id'], unique=False)
    op.create_table('edupay_fee_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fee_type', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('installment_plan', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='feeinstallmentplan'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('late_fee_rule', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edupay_fee_structures_id'), 'edupay_fee_structures', ['id'], unique=False)
    op.create_index(op.f('ix_edupay_fee_structures_school_id'), 'edupay_fee_structures', ['school_id'], unique=False)
    op.create_table('edupay_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edupay_parents_id'), 'edupay_parents', ['id'], unique=False)
    op.create_index(op.f('ix_edupay_parents_mobile_number'), 'edupay_parents', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_edupay_parents_school_id'), 'edupay_parents', ['school_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('total_batches', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostel_head', sa.String(length=255), nullable=True),
    sa.Column('warden_name', sa.String(length=255), nullable=True),
    sa.Column('gender_category', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_id'), 'hostels', ['id'], unique=False)
    op.create_index(op.f('ix_hostels_school_id'), 'hostels', ['school_id'], unique=False)
    op.create_table('inventory_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_subjects_id'), 'inventory_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_subjects_name'), 'inventory_subjects', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_subjects_school_id'), 'inventory_subjects', ['school_id'], unique=False)
    op.create_table('invigilators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invigilators_id'), 'invigilators', ['id'], unique=False)
    op.create_index(op.f('ix_invigilators_school_id'), 'invigilators', ['school_id'], unique=False)
    op.create_index(op.f('ix_invigilators_staff_id'), 'invigilators', ['staff_id'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('length_feet', sa.Float(), nullable=False),
    sa.Column('width_feet', sa.Float(), nullable=False),
    sa.Column('desk_length_feet', sa.Float(), nullable=False),
    sa.Column('desk_width_feet', sa.Float(), nullable=False),
    sa.Column('num_benches', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('teaching_zone_clearance_feet', sa.Float(), nullable=False),
    sa.Column('aisle_width_feet', sa.Float(), nullable=False),
    sa.Column('door_location', sa.Enum('left', 'right', 'top', 'bottom', 'top_left', 'top_right', 'bottom_left', 'bottom_right', name='doorlocation'), nullable=False),
    sa.Column('window_location', sa.String(length=50), nullable=True),
    sa.Column('glare_mitigation', sa.Boolean(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('principal_name', sa.String(length=255), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('auto_save', sa.Boolean(), nullable=False),
    sa.Column('conflict_detection', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('default_batch_colors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_school_id'), 'suppliers', ['school_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('attendance_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'PAID', 'EMERGENCY', name='leavetype'), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['attendance_staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_leaves_id'), 'attendance_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_leaves_school_id'), 'attendance_leaves', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_leaves_staff_member_id'), 'attendance_leaves', ['staff_member_id'], unique=False)
    op.create_table('desks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=True),
    sa.Column('reservation_reason', sa.String(length=255), nullable=True),
    sa.Column('x_position', sa.Float(), nullable=True),
    sa.Column('y_position', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_id'), 'desks', ['id'], unique=False)
    op.create_table('hostel_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=100), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_rooms_hostel_id'), 'hostel_rooms', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_hostel_rooms_id'), 'hostel_rooms', ['id'], unique=False)
    op.create_table('inventory_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['inventory_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sets_id'), 'inventory_sets', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_sets_name'), 'inventory_sets', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_sets_school_id'), 'inventory_sets', ['school_id'], unique=False)
    op.create_index(op.f('ix_inventory_sets_subject_id'), 'inventory_sets', ['subject_id'], unique=False)
    op.create_table('room_invigilators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('invigilator_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['invigilator_id'], ['invigilators.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_invigilators_id'), 'room_invigilators', ['id'], unique=False)
    op.create_index(op.f('ix_room_invigilators_invigilator_id'), 'room_invigilators', ['invigilator_id'], unique=False)
    op.create_index(op.f('ix_room_invigilators_room_id'), 'room_invigilators', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_invigilators_school_id'), 'room_invigilators', ['school_id'], unique=False)
    op.create_table('seating_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=True),
    sa.Column('students_assigned', sa.Integer(), nullable=True),
    sa.Column('batch_distribution', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seating_plans_id'), 'seating_plans', ['id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', name='staffattendancestatus'), nullable=False),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('marked_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['attendance_staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_attendance_date'), 'staff_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_id'), 'staff_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_school_id'), 'staff_attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_staff_member_id'), 'staff_attendance', ['staff_member_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='studentattendancestatus'), nullable=False),
    sa.Column('absence_reason', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['attendance_students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['attendance_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_date'), 'student_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_student_attendance_id'), 'student_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_student_attendance_school_id'), 'student_attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_subject_id'), 'student_attendance', ['subject_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('session_mode', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('extra_class_scope', sa.String(length=20), nullable=True),
    sa.Column('online_platform', sa.String(length=100), nullable=True),
    sa.Column('online_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_id'), 'timetable_entries', ['id'], unique=False)
    op.create_table('edupay_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('admission_no', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('boarding_type', sa.String(length=100), nullable=True),
    sa.Column('hostel_required', sa.Boolean(), nullable=False),
    sa.Column('preferred_hostel_id', sa.Integer(), nullable=True),
    sa.Column('hostel_request_status', sa.String(length=50), nullable=False),
    sa.Column('assigned_hostel_id', sa.Integer(), nullable=True),
    sa.Column('assigned_room_id', sa.Integer(), nullable=True),
    sa.Column('assigned_bed_label', sa.String(length=50), nullable=True),
    sa.Column('hostel_notes', sa.Text(), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('reference_remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['assigned_room_id'], ['hostel_rooms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['edupay_parents.id'], ),
    sa.ForeignKeyConstraint(['preferred_hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edupay_students_admission_no'), 'edupay_students', ['admission_no'], unique=False)
    op.create_index(op.f('ix_edupay_students_assigned_hostel_id'), 'edupay_students', ['assigned_hostel_id'], unique=False)
    op.create_index(op.f('ix_edupay_students_assigned_room_id'), 'edupay_students', ['assigned_room_id'], unique=False)
    op.create_index(op.f('ix_edupay_students_id'), 'edupay_students', ['id'], unique=False)
    op.create_index(op.f('ix_edupay_students_parent_id'), 'edupay_students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_edupay_students_preferred_hostel_id'), 'edupay_students', ['preferred_hostel_id'], unique=False)
    op.create_index(op.f('ix_edupay_students_school_id'), 'edupay_students', ['school_id'], unique=False)
    op.create_table('inventory_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['inventory_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_volumes_id'), 'inventory_volumes', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_volumes_school_id'), 'inventory_volumes', ['school_id'], unique=False)
    op.create_index(op.f('ix_inventory_volumes_set_id'), 'inventory_volumes', ['set_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('batch', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('academic_session', sa.String(length=50), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('special_needs', sa.Text(), nullable=True),
    sa.Column('requires_near_exit', sa.Boolean(), nullable=True),
    sa.Column('requires_extra_time', sa.Boolean(), nullable=True),
    sa.Column('boarding_type', sa.String(length=100), nullable=True),
    sa.Column('hostel_required', sa.Boolean(), nullable=False),
    sa.Column('preferred_hostel_id', sa.Integer(), nullable=True),
    sa.Column('hostel_request_status', sa.String(length=50), nullable=False),
    sa.Column('assigned_hostel_id', sa.Integer(), nullable=True),
    sa.Column('assigned_room_id', sa.Integer(), nullable=True),
    sa.Column('assigned_bed_label', sa.String(length=50), nullable=True),
    sa.Column('hostel_notes', sa.Text(), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('reference_remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['assigned_room_id'], ['hostel_rooms.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['preferred_hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_academic_session'), 'students', ['academic_session'], unique=False)
    op.create_index(op.f('ix_students_assigned_hostel_id'), 'students', ['assigned_hostel_id'], unique=False)
    op.create_index(op.f('ix_students_assigned_room_id'), 'students', ['assigned_room_id'], unique=False)
    op.create_index(op.f('ix_students_batch'), 'students', ['batch'], unique=False)
    op.create_index(op.f('ix_students_batch_id'), 'students', ['batch_id'], unique=False)
    op.create_index(op.f('ix_students_class_name'), 'students', ['class_name'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_preferred_hostel_id'), 'students', ['preferred_hostel_id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_index(op.f('ix_students_section'), 'students', ['section'], unique=False)
    op.create_table('edupay_fee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('installment_label', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('late_fee_applied', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', name='feeassignmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['edupay_fee_structures.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['edupay_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edupay_fee_assignments_fee_structure_id'), 'edupay_fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_edupay_fee_assignments_id'), 'edupay_fee_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_edupay_fee_assignments_school_id'), 'edupay_fee_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_edupay_fee_assignments_student_id'), 'edupay_fee_assignments', ['student_id'], unique=False)
    op.create_table('material_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('set_name', sa.String(length=255), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('volume_name', sa.String(length=255), nullable=True),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('set_part_name', sa.String(length=255), nullable=True),
    sa.Column('batch_names', sa.Text(), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('total_distributed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['inventory_sets.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['inventory_subjects.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['inventory_volumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_items_id'), 'material_items', ['id'], unique=False)
    op.create_index(op.f('ix_material_items_name'), 'material_items', ['name'], unique=False)
    op.create_index(op.f('ix_material_items_school_id'), 'material_items', ['school_id'], unique=False)
    op.create_index(op.f('ix_material_items_set_id'), 'material_items', ['set_id'], unique=False)
    op.create_index(op.f('ix_material_items_subject_id'), 'material_items', ['subject_id'], unique=False)
    op.create_index(op.f('ix_material_items_volume_id'), 'material_items', ['volume_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('student_hostel_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('requested_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_bed_label', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['hostel_rooms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_hostel_requests_hostel_id'), 'student_hostel_requests', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_student_hostel_requests_id'), 'student_hostel_requests', ['id'], unique=False)
    op.create_index(op.f('ix_student_hostel_requests_room_id'), 'student_hostel_requests', ['room_id'], unique=False)
    op.create_index(op.f('ix_student_hostel_requests_school_id'), 'student_hostel_requests', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_hostel_requests_student_id'), 'student_hostel_requests', ['student_id'], unique=False)
    op.create_table('edupay_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'CASH', 'CARD', 'BANK_TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='paymentverificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['edupay_fee_assignments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['edupay_students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edupay_payments_assignment_id'), 'edupay_payments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_edupay_payments_id'), 'edupay_payments', ['id'], unique=False)
    op.create_index(op.f('ix_edupay_payments_receipt_number'), 'edupay_payments', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_edupay_payments_school_id'), 'edupay_payments', ['school_id'], unique=False)
    op.create_index(op.f('ix_edupay_payments_student_id'), 'edupay_payments', ['student_id'], unique=False)
    op.create_table('stock_in_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material_items.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_in_entries_id'), 'stock_in_entries', ['id'], unique=False)
    op.create_index(op.f('ix_stock_in_entries_material_id'), 'stock_in_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_in_entries_school_id'), 'stock_in_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_stock_in_entries_supplier_id'), 'stock_in_entries', ['supplier_id'], unique=False)
    op.create_table('stock_out_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_items.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_out_entries_batch_id'), 'stock_out_entries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stock_out_entries_id'), 'stock_out_entries', ['id'], unique=False)
    op.create_index(op.f('ix_stock_out_entries_material_id'), 'stock_out_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_out_entries_school_id'), 'stock_out_entries', ['school_id'], unique=False)
    op.create_table('student_issue_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_items.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_issue_entries_batch_id'), 'student_issue_entries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_student_issue_entries_id'), 'student_issue_entries', ['id'], unique=False)
    op.create_index(op.f('ix_student_issue_entries_material_id'), 'student_issue_entries', ['material_id'], unique=False)
    op.create_index(op.f('ix_student_issue_entries_school_id'), 'student_issue_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_issue_entries_student_id'), 'student_issue_entries', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_issue_entries_student_id'), table_name='student_issue_entries')
    op.drop_index(op.f('ix_student_issue_entries_school_id'), table_name='student_issue_entries')
    op.drop_index(op.f('ix_student_issue_entries_material_id'), table_name='student_issue_entries')
    op.drop_index(op.f('ix_student_issue_entries_id'), table_name='student_issue_entries')
    op.drop_index(op.f('ix_student_issue_entries_batch_id'), table_name='student_issue_entries')
    op.drop_table('student_issue_entries')
    op.drop_index(op.f('ix_stock_out_entries_school_id'), table_name='stock_out_entries')
    op.drop_index(op.f('ix_stock_out_entries_material_id'), table_name='stock_out_entries')
    op.drop_index(op.f('ix_stock_out_entries_id'), table_name='stock_out_entries')
    op.drop_index(op.f('ix_stock_out_entries_batch_id'), table_name='stock_out_entries')
    op.drop_table('stock_out_entries')
    op.drop_index(op.f('ix_stock_in_entries_supplier_id'), table_name='stock_in_entries')
    op.drop_index(op.f('ix_stock_in_entries_school_id'), table_name='stock_in_entries')
    op.drop_index(op.f('ix_stock_in_entries_material_id'), table_name='stock_in_entries')
    op.drop_index(op.f('ix_stock_in_entries_id'), table_name='stock_in_entries')
    op.drop_table('stock_in_entries')
    op.drop_index(op.f('ix_edupay_payments_student_id'), table_name='edupay_payments')
    op.drop_index(op.f('ix_edupay_payments_school_id'), table_name='edupay_payments')
    op.drop_index(op.f('ix_edupay_payments_receipt_number'), table_name='edupay_payments')
    op.drop_index(op.f('ix_edupay_payments_id'), table_name='edupay_payments')
    op.drop_index(op.f('ix_edupay_payments_assignment_id'), table_name='edupay_payments')
    op.drop_table('edupay_payments')
    op.drop_index(op.f('ix_student_hostel_requests_student_id'), table_name='student_hostel_requests')
    op.drop_index(op.f('ix_student_hostel_requests_school_id'), table_name='student_hostel_requests')
    op.drop_index(op.f('ix_student_hostel_requests_room_id'), table_name='student_hostel_requests')
    op.drop_index(op.f('ix_student_hostel_requests_id'), table_name='student_hostel_requests')
    op.drop_index(op.f('ix_student_hostel_requests_hostel_id'), table_name='student_hostel_requests')
    op.drop_table('student_hostel_requests')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_material_items_volume_id'), table_name='material_items')
    op.drop_index(op.f('ix_material_items_subject_id'), table_name='material_items')
    op.drop_index(op.f('ix_material_items_set_id'), table_name='material_items')
    op.drop_index(op.f('ix_material_items_school_id'), table_name='material_items')
    op.drop_index(op.f('ix_material_items_name'), table_name='material_items')
    op.drop_index(op.f('ix_material_items_id'), table_name='material_items')
    op.drop_table('material_items')
    op.drop_index(op.f('ix_edupay_fee_assignments_student_id'), table_name='edupay_fee_assignments')
    op.drop_index(op.f('ix_edupay_fee_assignments_school_id'), table_name='edupay_fee_assignments')
    op.drop_index(op.f('ix_edupay_fee_assignments_id'), table_name='edupay_fee_assignments')
    op.drop_index(op.f('ix_edupay_fee_assignments_fee_structure_id'), table_name='edupay_fee_assignments')
    op.drop_table('edupay_fee_assignments')
    op.drop_index(op.f('ix_students_section'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_preferred_hostel_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_name'), table_name='students')
    op.drop_index(op.f('ix_students_batch_id'), table_name='students')
    op.drop_index(op.f('ix_students_batch'), table_name='students')
    op.drop_index(op.f('ix_students_assigned_room_id'), table_name='students')
    op.drop_index(op.f('ix_students_assigned_hostel_id'), table_name='students')
    op.drop_index(op.f('ix_students_academic_session'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_inventory_volumes_set_id'), table_name='inventory_volumes')
    op.drop_index(op.f('ix_inventory_volumes_school_id'), table_name='inventory_volumes')
    op.drop_index(op.f('ix_inventory_volumes_id'), table_name='inventory_volumes')
    op.drop_table('inventory_volumes')
    op.drop_index(op.f('ix_edupay_students_school_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_preferred_hostel_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_parent_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_assigned_room_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_assigned_hostel_id'), table_name='edupay_students')
    op.drop_index(op.f('ix_edupay_students_admission_no'), table_name='edupay_students')
    op.drop_table('edupay_students')
    op.drop_index(op.f('ix_timetable_entries_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_student_attendance_subject_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_school_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_date'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_staff_attendance_staff_member_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_school_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_seating_plans_id'), table_name='seating_plans')
    op.drop_table('seating_plans')
    op.drop_index(op.f('ix_room_invigilators_school_id'), table_name='room_invigilators')
    op.drop_index(op.f('ix_room_invigilators_room_id'), table_name='room_invigilators')
    op.drop_index(op.f('ix_room_invigilators_invigilator_id'), table_name='room_invigilators')
    op.drop_index(op.f('ix_room_invigilators_id'), table_name='room_invigilators')
    op.drop_table('room_invigilators')
    op.drop_index(op.f('ix_inventory_sets_subject_id'), table_name='inventory_sets')
    op.drop_index(op.f('ix_inventory_sets_school_id'), table_name='inventory_sets')
    op.drop_index(op.f('ix_inventory_sets_name'), table_name='inventory_sets')
    op.drop_index(op.f('ix_inventory_sets_id'), table_name='inventory_sets')
    op.drop_table('inventory_sets')
    op.drop_index(op.f('ix_hostel_rooms_id'), table_name='hostel_rooms')
    op.drop_index(op.f('ix_hostel_rooms_hostel_id'), table_name='hostel_rooms')
    op.drop_table('hostel_rooms')
    op.drop_index(op.f('ix_desks_id'), table_name='desks')
    op.drop_table('desks')
    op.drop_index(op.f('ix_attendance_leaves_staff_member_id'), table_name='attendance_leaves')
    op.drop_index(op.f('ix_attendance_leaves_school_id'), table_name='attendance_leaves')
    op.drop_index(op.f('ix_attendance_leaves_id'), table_name='attendance_leaves')
    op.drop_table('attendance_leaves')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_suppliers_school_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_invigilators_staff_id'), table_name='invigilators')
    op.drop_index(op.f('ix_invigilators_school_id'), table_name='invigilators')
    op.drop_index(op.f('ix_invigilators_id'), table_name='invigilators')
    op.drop_table('invigilators')
    op.drop_index(op.f('ix_inventory_subjects_school_id'), table_name='inventory_subjects')
    op.drop_index(op.f('ix_inventory_subjects_name'), table_name='inventory_subjects')
    op.drop_index(op.f('ix_inventory_subjects_id'), table_name='inventory_subjects')
    op.drop_table('inventory_subjects')
    op.drop_index(op.f('ix_hostels_school_id'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_edupay_parents_school_id'), table_name='edupay_parents')
    op.drop_index(op.f('ix_edupay_parents_mobile_number'), table_name='edupay_parents')
    op.drop_index(op.f('ix_edupay_parents_id'), table_name='edupay_parents')
    op.drop_table('edupay_parents')
    op.drop_index(op.f('ix_edupay_fee_structures_school_id'), table_name='edupay_fee_structures')
    op.drop_index(op.f('ix_edupay_fee_structures_id'), table_name='edupay_fee_structures')
    op.drop_table('edupay_fee_structures')
    op.drop_index(op.f('ix_batches_school_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_name'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_display_order'), table_name='batches')
    op.drop_index(op.f('ix_batches_category'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_attendance_subjects_section'), table_name='attendance_subjects')
    op.drop_index(op.f('ix_attendance_subjects_school_id'), table_name='attendance_subjects')
    op.drop_index(op.f('ix_attendance_subjects_id'), table_name='attendance_subjects')
    op.drop_index(op.f('ix_attendance_subjects_class_name'), table_name='attendance_subjects')
    op.drop_table('attendance_subjects')
    op.drop_index(op.f('ix_attendance_students_section'), table_name='attendance_students')
    op.drop_index(op.f('ix_attendance_students_school_id'), table_name='attendance_students')
    op.drop_index(op.f('ix_attendance_students_roll_no'), table_name='attendance_students')
    op.drop_index(op.f('ix_attendance_students_id'), table_name='attendance_students')
    op.drop_index(op.f('ix_attendance_students_class_name'), table_name='attendance_students')
    op.drop_table('attendance_students')
    op.drop_index(op.f('ix_attendance_staff_staff_id'), table_name='attendance_staff')
    op.drop_index(op.f('ix_attendance_staff_school_id'), table_name='attendance_staff')
    op.drop_index(op.f('ix_attendance_staff_id'), table_name='attendance_staff')
    op.drop_index(op.f('ix_attendance_staff_department'), table_name='attendance_staff')
    op.drop_table('attendance_staff')
    op.drop_index(op.f('ix_attendance_settings_school_id'), table_name='attendance_settings')
    op.drop_index(op.f('ix_attendance_settings_id'), table_name='attendance_settings')
    op.drop_table('attendance_settings')
    op.drop_index(op.f('ix_attendance_notifications_school_id'), table_name='attendance_notifications')
    op.drop_index(op.f('ix_attendance_notifications_id'), table_name='attendance_notifications')
    op.drop_table('attendance_notifications')
    op.drop_index(op.f('ix_attendance_holidays_school_id'), table_name='attendance_holidays')
    op.drop_index(op.f('ix_attendance_holidays_id'), table_name='attendance_holidays')
    op.drop_index(op.f('ix_attendance_holidays_holiday_date'), table_name='attendance_holidays')
    op.drop_table('attendance_holidays')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_email'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
